apiVersion: v1
kind: ConfigMap
metadata:
  name: alpha-cm
data:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres123"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://psql15-svc/postgres"
  