{{- if .Values.alpha.deploy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alpha.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "alpha.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "alpha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alpha.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.alpha.name}}
          image: "{{ .Values.alpha.deploy.image.repository }}:{{ .Values.alpha.deploy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.alpha.deploy.image.pullPolicy }}
          ports:
            - name: {{ .Values.alpha.name }}-http
              containerPort: {{ .Values.alpha.service.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "alpha.configMapName" . }}
{{- end }}