apiVersion: v1
kind: Service
metadata:
  name: psql15-svc
spec:
  selector:
    app: psql15
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
  