{{- if .Values.db.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.configMapName" . }}
  namespace: {{ .Values.namespace.name }}
data:
  {{- range $key, $val := .Values.db.deploy.environments }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}