{{- if .Values.db.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.db.name}}
          image: "{{ .Values.db.deploy.image.repository }}:{{ .Values.db.deploy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.deploy.image.pullPolicy }}
          ports:
            - name: {{ .Values.db.name }}-http
              containerPort: {{ .Values.db.service.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                  name: {{ include "db.configMapName" . }}

{{- end }}