{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.serviceName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.name }}-http
      protocol: TCP
      name: http
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
{{- end }}